#!/usr/bin/awk -f

/^#/ {
    next
}

# Exclude long URLs from maximum line length check
/^([*-]|\[[0-9]]:)? *https?:/ {
    LINES++
    next
}

/^.{73}/ {
    printf("%s:%d: Line exceeds 72 columns\n", FILENAME, FNR)
    exit 1
}

/^$/ {
    LINES++
    next
}

{
    if (++LINES == 2) {
        printf("%s: line #2 should always be blank\n", FILENAME)
        exit 1
    }
}
