#!/bin/sh

# This pre-commit hook creates a fresh, temporary checkout of the index
# (i.e. not including unstaged/dirty changes from the working tree)
# and then performs a full build.

TMPDIR='.pre-commit-test'
PROGNAME="$0"

abort() {
    echo "$PROGNAME:$2: Error: $1" >&2
    exit 1
}

test ! -e "$TMPDIR" || abort "path '$TMPDIR' already exists" $LINENO

MAKE="$(command -v gmake || command -v make)"
test -x "$MAKE" || abort 'unable to find GNU Make command' $LINENO

git checkout-index --prefix="$TMPDIR/" -a || exit 1
trap "rm -rf '$TMPDIR'" EXIT

GENERATED="$TMPDIR/docs/*.[15] $TMPDIR/src/lookup/*.c"
cp $GENERATED "$TMPDIR"

$MAKE -B -j"$(mk/nproc.sh)" -C"$TMPDIR" man gen check check-syntax-files

for F in $GENERATED; do
    B="$(basename $F)"
    if ! diff "$F" "$TMPDIR/$B" >/dev/null; then
        abort "re-generate '${F##${TMPDIR}/}' before committing" $LINENO
    fi
done
