#!/bin/sh

# This pre-commit hook creates a fresh, temporary checkout of the index
# (i.e. not including unstaged/dirty changes from the working tree)
# and then performs a full build.

TMPDIR='.pre-commit-test'
PROGNAME="$0"

abort() {
    echo "$PROGNAME:$2: Error: $1" >&2
    exit 1
}

test ! -e "$TMPDIR" || abort "path '$TMPDIR' already exists" $LINENO

MAKE="$(command -v gmake || command -v make)"
test -x "$MAKE" || abort 'unable to find GNU Make command' $LINENO
MAKE="$MAKE --no-print-directory -C $TMPDIR -j$(mk/nproc.sh)"

git checkout-index --prefix="$TMPDIR/" -a || exit 1
trap "rm -rf '$TMPDIR'" EXIT

GENERATED=''
for G in $(git ls-files --error-unmatch ':(attr:is-generated)'); do
    GENERATED="$GENERATED $TMPDIR/$G"
done

mkdir -p "$TMPDIR/GEN/"
cp $GENERATED "$TMPDIR/GEN/"
$MAKE -B gen man

for F in $GENERATED; do
    B="$(basename $F)"
    if ! diff "$F" "$TMPDIR/GEN/$B" >/dev/null; then
        abort "re-generate '${F##${TMPDIR}/}' before committing" $LINENO
    fi
done

$MAKE -B check check-syntax-files WERROR=1
$MAKE check WERROR=1 TERMINFO_DISABLE=1
