stages: [test, dist]

default:
    before_script:
        - git fetch --tags
        - export MAKEFLAGS="-j$(mk/nproc.sh)" DEBUG=3 WERROR=1 V=1
        - make vars

.test:
    stage: test
    script:
        - make check
        - ldd dte
        - make clean && make check LDFLAGS=-static
        - ldd dte || true
        - make clean && make check CSTD='-std=c99 -D_POSIX_C_SOURCE=200809L'
        - make clean && make DEBUG=0 && make installcheck
        - strip dte && du -k -h dte
        - tools/objsize.sh dte

alpine:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-alpine

arch:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-arch

centos-7:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-centos-7

centos-8:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-centos-8

ubuntu:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-ubuntu

debian-9:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian-9
    script:
        - make check
        - make installcheck
        - make check-syntax-files
        - make clean && make check CC=gcc
        - make clean && make check CC=clang
        - make clean && make CC=arm-linux-gnueabihf-gcc
        - make clean && make CC=aarch64-linux-gnu-gcc
        - export LDFLAGS=-static
        - make clean && make check CC=gcc
        - make clean && make check CC=clang
        - make clean && make CC=arm-linux-gnueabihf-gcc
        - make clean && make CC=aarch64-linux-gnu-gcc
        - make clean && make distcheck

debian-10:
    extends: debian-9
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian-10

android:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/android-ndk
    script:
        - make clean && make CC="$CC_ARMV7A"
        - make clean && make CC="$CC_AARCH64"
        - make clean && make CC="$CC_I686"
        - make clean && make CC="$CC_X86_64"

.pages:
    stage: dist
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian
    coverage: '/^ *lines\.*: *(\d+\.\d+\%) .*$/'
    artifacts:
        paths: [public]
        expire_in: 60 days
        name: dte-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA
    script:
        - make docs
        - make coverage-report
        - make vars check CC=musl-gcc LDFLAGS=-static DEBUG=0 SANE_WCTYPE=1
        - strip dte
        - tools/objsize.sh dte
        - ldd dte || true
        - TARNAME="$(./dte -V | head -n1 | tr -- ' ' -)-linux-$(uname -m)"
        - tar -czf "public/$TARNAME.tar.gz" dte docs/dte.1 docs/dterc.5 docs/dte-syntax.5
        - ln -s "$TARNAME.tar.gz" public/dte-master-linux-$(uname -m).tar.gz
        - tree public/

pages:
    extends: .pages
    only: [master]

pages:non-master:
    extends: .pages
    except: [master]
