stages: [build, dist]

build:alpine:
    stage: build
    image: alpine:3.6
    script:
        - mk/install-deps.sh
        - make vars
        - make -j`mk/nproc.sh` check V=1
        - make install
        - dte -V
        - make clean
        - make -j`mk/nproc.sh` check V=1 TERMINFO_DISABLE=1
        - ./dte -V

build:centos:
    stage: build
    image: centos:7
    script:
        - mk/install-deps.sh
        - make vars
        - make -j`mk/nproc.sh` check V=1
        - make install
        - dte -V
        - make clean
        - make -j`mk/nproc.sh` check V=1 TERMINFO_DISABLE=1
        - ./dte -V

build:debian:
    stage: build
    image: debian:stretch
    variables: {DEBIAN_FRONTEND: noninteractive}
    script:
        - mk/install-deps.sh
        - make vars
        - make -j`mk/nproc.sh` check V=1
        - make install
        - dte -V
        - make clean
        - make -j`mk/nproc.sh` check V=1 TERMINFO_DISABLE=1
        - ./dte -V

build:ubuntu:
    stage: build
    image: ubuntu:16.04
    variables: {DEBIAN_FRONTEND: noninteractive}
    script:
        - mk/install-deps.sh
        - make vars
        - make -j`mk/nproc.sh` check V=1
        - make install
        - dte -V
        - make clean
        - make -j`mk/nproc.sh` check V=1 TERMINFO_DISABLE=1
        - ./dte -V

pages:
    stage: dist
    image: alpine:3.6
    artifacts: {paths: [public]}
    only: [master]
    script:
        - apk --update add make gcc binutils libc-dev groff gzip
        - make -j`mk/nproc.sh` docs V=1
