stages: [test, dist]

default:
    interruptible: true
    before_script:
        - export DEBUG=3 WERROR=1 V=1 TESTFLAGS=-ct
        - export CC="ccache ${CC:-gcc}"
        # Ensure upstream "v*" tags are present, regardless of whether
        # this job is running for a fork or the upstream repo
        - git fetch https://gitlab.com/craigbarnes/dte.git 'refs/tags/v*:refs/tags/v*'
        - make vvars || (make dump-generated-makefiles; exit 1)

.fragment-1:
    script: &objsize_and_bench
        - make DEBUG=0 && make installcheck
        - strip dte && du -k -h dte
        - tools/objsize.sh dte
        - make bench DEBUG=0 CFLAGS=-O3

.test:
    stage: test
    needs: []
    script:
        - make
        - cat build/gen/feature.h
        - ldd dte
        - make check
        - make check LDFLAGS=-static
        - *objsize_and_bench

alpine:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-alpine

ubuntu:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-ubuntu

rocky-8:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-rocky-8

rocky-9:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-rocky-9

debian-oldstable:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian-oldstable

arch:
    stage: test
    needs: []
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-arch
    script:
        - make check-source check-clang-tidy
        - make check USE_SANITIZER=1
        - (cd build/ && test/test)
        - *objsize_and_bench

debian-stable:
    stage: test
    needs: []
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian
    script:
        - make check CC='ccache clang'
        - make check CC='ccache clang' LDFLAGS=-static
        - make check CC='ccache gcc'
        - make check CC='ccache gcc' LDFLAGS=-static
        - make check
        - make installcheck

        # Ensure build works with no detected features (test fallbacks)
        - cat build/gen/feature.h
        - sed 's/ 1$/ 0/' build/gen/feature.h > build/gen/feature-tmp.h
        - mv build/gen/feature-tmp.h build/gen/feature.h
        - make check
        - cat build/gen/feature.h

        # Build with ARM cross-compilers
        - make CC='ccache arm-linux-gnueabihf-gcc'
        - make CC='ccache arm-linux-gnueabihf-gcc' LDFLAGS=-static
        - make CC='ccache aarch64-linux-gnu-gcc'
        - make CC='ccache aarch64-linux-gnu-gcc' LDFLAGS=-static

        - make clean && make distcheck
        - make bench DEBUG=0 CFLAGS=-O3

android:
    stage: test
    needs: []
    image: registry.gitlab.com/craigbarnes/dockerfiles/android-ndk
    script:
        - make CC="$CC_AARCH64"
        - cat build/gen/feature.h
        - make CC="$CC_ARMV7A"
        - make CC="$CC_I686"
        - make CC="$CC_X86_64"

coverage:
    stage: test
    needs: []
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-alpine
    artifacts:
        expire_in: 30 days
        name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
        reports:
            coverage_report:
                coverage_format: cobertura
                path: build/coverage.xml
    script:
        - make gcovr-xml
        - awk -f tools/gcovr-txt.awk build/coverage.txt

.pages:
    stage: dist
    needs: []
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-arch
    coverage: '/^ *lines\.*: *(\d+\.\d+\%) .*$/'
    artifacts:
        paths: [public]
        expire_in: 60 days
        name: dte-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA
    script:
        - make docs htmlgz-aux
        - make gcovr-html
        - make vvars check CC=musl-gcc LDFLAGS=-static DEBUG=0 SANE_WCTYPE=1
        - strip dte
        - tools/objsize.sh dte
        - ldd dte || true
        - TARNAME="$(./dte -V | head -n1 | tr -- ' ' -)-linux-$(uname -m)"
        - tar -czf "public/$TARNAME.tar.gz" dte docs/dte.1 docs/dterc.5 docs/dte-syntax.5
        - ln -s "$TARNAME.tar.gz" public/dte-master-linux-$(uname -m).tar.gz
        - tree public/

pages:
    extends: .pages
    rules:
        - if: $CI_COMMIT_BRANCH == "master"

pages:non-master:
    extends: .pages
    rules:
        - if: $CI_COMMIT_BRANCH != "master"
