stages: [test, dist]

default:
    before_script:
        - git fetch --tags
        - export MAKEFLAGS="-j$(mk/nproc.sh)" DEBUG=3 WERROR=1 V=1
        - make vars

.test:
    stage: test
    script:
        - make check TERMINFO_DISABLE=1
        - ldd dte
        - make clean && make check TERMINFO_DISABLE=1 LDFLAGS=-static
        - ldd dte || true
        - make clean && make check USE_SANITIZER=1
        - ldd dte
        - make clean && make check CSTD='-std=c99'
        - make clean && make DEBUG=0 && make install && dte -V
        - strip dte && du -k -h dte
        - tools/objsize.sh dte

alpine:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-alpine

centos:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-centos

ubuntu:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-ubuntu

void-musl:
    extends: .test
    image:
        name: registry.gitlab.com/craigbarnes/dockerfiles/cdev-void-musl
        entrypoint: []

debian:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian
    script:
        - make check && make install && dte -V
        - make check-syntax-files
        - export TERMINFO_DISABLE=1
        - make clean && make check CC=gcc
        - make clean && make check CC=clang
        - make clean && make check CC=tcc
        - make clean && make dte CC=arm-linux-gnueabihf-gcc
        - make clean && make dte CC=aarch64-linux-gnu-gcc
        - export LDFLAGS=-static
        - make clean && make check CC=gcc
        - make clean && make check CC=clang
        - make clean && make dte CC=arm-linux-gnueabihf-gcc
        - make clean && make dte CC=aarch64-linux-gnu-gcc
        - make clean && make distcheck

android:
    extends: .test
    image: registry.gitlab.com/craigbarnes/dockerfiles/android-ndk
    script:
        - export TERMINFO_DISABLE=1
        - make clean && make CC="$CC_ARMV7A"
        - make clean && make CC="$CC_AARCH64"
        - make clean && make CC="$CC_I686"
        - make clean && make CC="$CC_X86_64"

.pages:
    stage: dist
    image: registry.gitlab.com/craigbarnes/dockerfiles/cdev-debian
    artifacts: {paths: [public]}
    coverage: '/^ *lines\.*: *(\d+\.\d+\%) .*$/'
    script:
        - make docs
        - make coverage-report
        - make vars check CC=musl-gcc LDFLAGS=-static TERMINFO_DISABLE=1 DEBUG=0
        - strip dte
        - tools/objsize.sh dte
        - ldd dte || true
        - TARNAME="$(./dte -V | head -n1 | tr -- ' ' -)-linux-$(uname -m)"
        - tar -czf "public/$TARNAME.tar.gz" dte docs/dte.1 docs/dterc.5 docs/dte-syntax.5
        - ln -s "$TARNAME.tar.gz" public/dte-master-linux-$(uname -m).tar.gz
        - tree public/

pages:
    extends: .pages
    only: [master]

pages:non-master:
    extends: .pages
    except: [master]
    artifacts: {expire_in: 1 week}
