stages: [build, dist]

build:alpine:
    stage: build
    image: alpine:3.6
    script:
        - apk --update add make gcc binutils ncurses
        - make -j`nproc` V=1
        - make install
        - dte -V

build:centos:
    stage: build
    image: centos:7
    script:
        - yum makecache
        - yum -y install make gcc binutils ncurses-devel
        - make -j`nproc` V=1
        - make install
        - dte -V

build:debian:
    stage: build
    image: debian:stretch
    variables: {DEBIAN_FRONTEND: noninteractive}
    script:
        - apt-get update
        - apt-get -qy install make gcc binutils libncurses5-dev
        - make -j`nproc` V=1
        - make install
        - dte -V

pages:
    stage: dist
    image: debian:stretch
    artifacts: {paths: [public]}
    only: [master]
    variables: {DEBIAN_FRONTEND: noninteractive}
    script:
        - apt-get update
        - apt-get -qy install make gcc binutils git groff tar gzip
        - git fetch --tags
        - make -j`nproc` html dist V=1
        - make check-dist
