stages: [build, dist]

build:alpine:
    stage: build
    image: alpine:3.6
    script: &SCRIPT
        - mk/install-deps.sh
        - make vars
        - make -j`mk/nproc.sh` check V=1
        - make install
        - dte -V
        - strip dte && ls -lh dte
        - size dte
        - ldd dte
        - readelf -h dte
        - make clean
        - make -j`mk/nproc.sh` check V=1 TERMINFO_DISABLE=1
        - ./dte -V
        - strip dte && ls -lh dte
        - size dte
        - ldd dte
        - readelf -h dte

build:centos:
    stage: build
    image: centos:7
    script: *SCRIPT

build:debian:
    stage: build
    image: debian:stretch
    variables: {DEBIAN_FRONTEND: noninteractive}
    script: *SCRIPT

build:ubuntu:
    stage: build
    image: ubuntu:16.04
    variables: {DEBIAN_FRONTEND: noninteractive}
    script: *SCRIPT

pages:
    stage: dist
    image: alpine:3.6
    artifacts: {paths: [public]}
    only: [master]
    script:
        - apk --update add make gcc binutils libc-dev groff gzip
        - make -j`mk/nproc.sh` docs V=1
        - make -j`mk/nproc.sh` TERMINFO_DISABLE=1 CC=gcc LDFLAGS='--static' V=1
        - strip dte
        - ls -lh dte
        - size dte
        - readelf -h dte
        - cp dte public/dte-linux-$(uname -m)
