stages: [build, dist]

build:alpine:
    stage: build
    image: alpine:3.6
    script: &SCRIPT
        - mk/install-deps.sh
        - export MAKEFLAGS="-j$(mk/nproc.sh)" WERROR=1 V=1
        - make vars check
        - make install
        - dte -V
        - strip dte && du -h dte
        - ldd dte
        - make clean && make uninstall
        - make vars check TERMINFO_DISABLE=1
        - make install
        - dte -V
        - strip dte && du -h dte
        - ldd dte

build:debian:
    stage: build
    image: debian:stretch
    variables: {DEBIAN_FRONTEND: noninteractive}
    script:
        - mk/install-deps.sh
        - apt-get -qy install gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
        - export MAKEFLAGS="-j$(mk/nproc.sh)" WERROR=1 V=1
        - make vars check
        - export TERMINFO_DISABLE=1
        - make clean && make vars dte CC=gcc
        - make clean && make vars dte CC=arm-linux-gnueabihf-gcc
        - make clean && make vars dte CC=aarch64-linux-gnu-gcc

build:centos:
    stage: build
    image: centos:7
    script: *SCRIPT

build:ubuntu:
    stage: build
    image: ubuntu:16.04
    variables: {DEBIAN_FRONTEND: noninteractive}
    script: *SCRIPT

pages:
    stage: dist
    image: alpine:3.6
    artifacts: {paths: [public]}
    only: [master]
    script: &PAGES_SCRIPT
        - apk --update add git make gcc binutils libc-dev groff gzip
        - git fetch --tags
        - make -j`mk/nproc.sh` docs V=1
        - make -j`mk/nproc.sh` vars check TERMINFO_DISABLE=1 CC=gcc LDFLAGS='--static' V=1
        - strip dte
        - ls -lh dte
        - size dte
        - ldd dte || true
        - readelf -h dte
        - cp dte public/dte-linux-$(uname -m)

# Same as "pages" but without public artifacts (for testing non-master branches)
pages:non-master:
    stage: build
    image: alpine:3.6
    except: [master]
    script: *PAGES_SCRIPT
