language: c
sudo: false
os: [linux, osx]
compiler: [clang, gcc]
script:
    - make vars
    - make -j`mk/nproc.sh` check V=1
    - make install DESTDIR="$PWD/pkgdir"
    - pkgdir/usr/local/bin/dte -V
    - make clean
    - make -j`mk/nproc.sh` check V=1 TERMINFO_DISABLE=1
    - ./dte -V
