language: c
sudo: false
os: [linux, osx]
compiler: [clang, gcc]
script:
    - export V=1 NO_DEPS=y
    - make -j`mk/nproc.sh`
    - make install DESTDIR="$PWD/pkgdir"
    - pkgdir/usr/local/bin/dte -V
