language: c
sudo: false
git: {depth: false}
os: [linux, osx]
arch: [amd64, arm64, ppc64le, s390x]
compiler: [clang, gcc]
script:
    - git fetch --tags
    - make vars
    - make -j`mk/nproc.sh` check V=1
    - make install DESTDIR="$PWD/pkgdir"
    - pkgdir/usr/local/bin/dte -V
    - make clean
    - make -j`mk/nproc.sh` check V=1 TERMINFO_DISABLE=1
    - ./dte -V
