language: c
sudo: required
os: [linux]
compiler: [clang, gcc]
install:
    - sudo apt-get update
    - sudo apt-get -qy install make gcc binutils libncurses5-dev git groff tar gzip
script:
    - git fetch --tags
    - make -j`nproc` all html dist V=1
    - sudo make install
    - dte -V
    - make check-dist
