language: c
git: {depth: false}
os: [linux, osx]
arch: [amd64, arm64, ppc64le, s390x]
compiler: [clang, gcc]

script:
    - git fetch --tags
    - export MAKE="$(command -v gmake || command -v make)"
    - export MAKEFLAGS="-j$(mk/nproc.sh)" DEBUG=3 WERROR=1 V=1
    - $MAKE vars
    - $MAKE check
    - cat build/feature.h
    - ./dte -V
    - $MAKE check ICONV_DISABLE=1
    - $MAKE distcheck
