language: c
git: {depth: false}
os: [linux, osx]
arch: [amd64, arm64, ppc64le, s390x]
compiler: [clang, gcc]

script:
    - git fetch --tags
    - export MAKE="$(command -v gmake || command -v make)"
    - export MAKEFLAGS="-j$(mk/nproc.sh)" DEBUG=3 WERROR=1 V=1
    - $MAKE vars
    - $MAKE check
    - cat build/feature.h
    - ./dte -V
    - $MAKE check ICONV_DISABLE=1
    # This test fails on the default OS X runner due to an obsolete
    # version of GNU Make (3.81):
    - if test "$TRAVIS_OS_NAME" != osx; then make distcheck; fi
