[type.c]
extend-glob = ["*.c", "*.h"]
extend-ignore-words-re = [
    "^BRE|Pn|clen|doas|ede|mak|typ$",
    "^(?i:iterm)$",
]

[type.devmk]
extend-glob = ["dev.mk"]
extend-ignore-words-re = ["^clen|ede$"]
