#!/bin/sh
# The output of this script is used to generate build/gen/compiler.mk
# shellcheck disable=SC2086,SC2116,SC2310

set -eu
CC="$1"

SANITIZER_FLAGS='
    -fsanitize=address,undefined -fsanitize-address-use-after-scope
    -fno-sanitize-recover=all -fno-omit-frame-pointer -fno-common
'

cc_option() {
    $CC "$@" -Werror -c -o /dev/null mk/feature-test/basic.c
}

echo '# Generated by mk/compiler.sh; do not edit'

if cc_option -std=gnu23; then
    echo 'BASIC_CFLAGS += -std=gnu23'
else
    echo 'BASIC_CFLAGS += -std=gnu11'
fi

if cc_option -fvisibility=hidden; then
    echo 'BASIC_CFLAGS += -fvisibility=hidden'
fi

if cc_option -MMD -MP -MF /dev/null; then
    echo 'DEPFLAGS = -MMD -MP -MF $(@:.o=.mk)'
elif cc-option -MD -MF /dev/null; then
    echo 'DEPFLAGS = -MD -MF $(@:.o=.mk)'
fi

if cc_option -fno-asynchronous-unwind-tables; then
    echo "NO_UNWIND_TABLES = -fno-asynchronous-unwind-tables"
fi

# $(echo ...) is used here to remove newlines and extra spaces
SANITIZER_FLAGS="$(echo $SANITIZER_FLAGS)"

if cc_option $SANITIZER_FLAGS; then
    echo "CC_SANITIZER_FLAGS = $SANITIZER_FLAGS"
fi
