#!/bin/sh
# The output of this script is used to generate build/gen/compiler.mk
# shellcheck disable=SC2086,SC2116,SC2310

set -eu
CC="$1"

# These options are divided into "sets" and are tested all at once,
# to keep the process spawning overhead to a minimum (i.e. as compared
# to iterating through and checking them individually)
GCC_14_WARNINGS='
    -Walloca -Walloc-zero -Wnull-dereference -Wformat-signedness
    -Wstringop-truncation -Wstringop-overflow -Wshift-overflow=2
    -Wcast-align=strict -Wduplicated-branches -Wduplicated-cond
    -Wlogical-op -Wmissing-noreturn -Wdate-time -Wtrampolines
'

CLANG_18_WARNINGS='
    -Walloca -Wnull-dereference -Wcomma -Wmissing-noreturn -Wdate-time
'

SANITIZER_FLAGS='
    -fsanitize=address,undefined -fsanitize-address-use-after-scope
    -fno-sanitize-recover=all -fno-omit-frame-pointer -fno-common
'

cc_option() {
    $CC "$@" -Werror -c -o /dev/null mk/feature-test/basic.c
}

fmt_cflags() {
    echo "$1" | sed -E '/^$/d; s/^ */BASIC_CFLAGS += /'
}

echo '# Generated by mk/compiler.sh; do not edit'

if cc_option -std=gnu23; then
    echo 'BASIC_CFLAGS += -std=gnu23'
else
    echo 'BASIC_CFLAGS += -std=gnu11'
fi

if cc_option -fvisibility=hidden; then
    echo 'BASIC_CFLAGS += -fvisibility=hidden'
fi

if cc_option $GCC_14_WARNINGS; then
    fmt_cflags "$GCC_14_WARNINGS"
elif cc_option $CLANG_18_WARNINGS; then
    fmt_cflags "$CLANG_18_WARNINGS"
fi

if cc_option -MMD -MP -MF /dev/null; then
    echo 'DEPFLAGS = -MMD -MP -MF $(@:.o=.mk)'
elif cc-option -MD -MF /dev/null; then
    echo 'DEPFLAGS = -MD -MF $(@:.o=.mk)'
fi

if cc_option -fno-asynchronous-unwind-tables; then
    echo "NO_UNWIND_TABLES = -fno-asynchronous-unwind-tables"
fi

# $(echo ...) is used here to remove newlines and extra spaces
SANITIZER_FLAGS="$(echo $SANITIZER_FLAGS)"

if cc_option $SANITIZER_FLAGS; then
    echo "CC_SANITIZER_FLAGS = $SANITIZER_FLAGS"
fi
