#!/bin/sh
# The output of this script is used to generate build/gen/platform.mk

set -u
LOGFILE="$1"
KERNEL="$(uname -s)"
NPROC="$(mk/nproc.sh)"

# Truncate log file, before appending to it
printf '' >"$LOGFILE"

echo "# Generated by mk/platform.sh; do not edit
KERNEL = ${KERNEL:-unknown}
NPROC = ${NPROC:-1}"

# Check for `xargs -P` (parallel execution) support.
# This has been resolved as "accepted as marked" for POSIX issue 9:
# • https://austingroupbugs.net/view.php?id=1801
# • https://austingroupbugs.net/view.php?id=1811
if test "$NPROC" -gt 1 && printf "1\n2" | xargs -P2 -I@ echo '@' >/dev/null 2>>"$LOGFILE"; then
    XARGS_PFLAG=" -P$NPROC"
fi

echo "XARGS_P = xargs${XARGS_PFLAG:-}"
