#!/bin/sh
# The output of this script is used to generate build/gen/platform.mk

set -u
KERNEL="$(uname -s)"
NPROC="$(mk/nproc.sh)"

echo "# Generated by mk/platform.sh; do not edit

KERNEL = ${KERNEL:-unknown}
NPROC = ${NPROC:-1}
"

case "$KERNEL" in
Darwin)
    echo 'LDLIBS_ICONV = -liconv' ;;
OpenBSD)
    echo 'LDLIBS_ICONV = -liconv'
    echo 'BASIC_CPPFLAGS += -I/usr/local/include'
    echo 'BASIC_LDFLAGS += -L/usr/local/lib' ;;
NetBSD)
    echo 'BASIC_CPPFLAGS += -I/usr/pkg/include'
    echo 'BASIC_LDFLAGS += -L/usr/pkg/lib' ;;
CYGWIN*)
    echo 'LDLIBS_ICONV = -liconv'
    echo 'EXEC_SUFFIX = .exe' ;;
esac
