#!/usr/bin/awk -f

BEGIN {
    LINES = 0
}

/^#/ {
    next
}

/^.{73}/ {
    printf("%s:%d: Line exceeds 72 columns\n", FILENAME, FNR)
    exit 1
}

/^$/ {
    LINES++
    next
}

{
    if (++LINES == 2) {
        printf("%s: line #2 should be blank; see docs/CONTRIBUTING.md\n", FILENAME)
        exit 1
    }
}
