name: Test
on: [push]

env:
    V: 1
    DEBUG: 3
    WERROR: 1
    TESTFLAGS: -ct

jobs:
    macos:
        strategy:
            matrix:
                os: [macos-14, macos-13, macos-12]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - run: brew install make
            - run: gmake vars
            - run: gmake build/gen/feature.h
            - run: cat build/gen/feature.h build/feature/*.log
            - run: gmake -Otarget check
            - run: gmake bench CFLAGS=-O3 DEBUG=0

    linux:
        strategy:
            matrix:
                os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - run: make vars
            - run: make build/gen/feature.h
            - run: cat build/gen/feature.h build/feature/*.log
            - run: make -Otarget check
            - run: make bench CFLAGS=-O3 DEBUG=0
