name: Test
on: [push]
jobs:
    check:
        strategy:
            matrix:
                os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11]
        steps:
            - uses: actions/checkout@v3
            - run: make check V=1 DEBUG=3 WERROR=1
