name: Test
on: [push]

jobs:
    macos:
        strategy:
            matrix:
                os: [macos-26, macos-15, macos-15-intel, macos-14]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
              with: {filter: "tree:0", fetch-depth: 0}
            - run: ln -s tools/Config-CI.mk Config.mk
            - run: brew install make
            - run: gmake vvars
            - run: gmake build/gen/build-defs.h
            - run: cat build/gen/build-defs.h build/feature/*.log
            - run: gmake check
            - run: gmake bench CFLAGS=-O3 DEBUG=0

    linux:
        strategy:
            matrix:
                os: [ubuntu-24.04, ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
              with: {filter: "tree:0", fetch-depth: 0}
            - run: ln -s tools/Config-CI.mk Config.mk
            - run: make vvars
            - run: make build/gen/build-defs.h
            - run: cat build/gen/build-defs.h build/feature/*.log
            - run: make check
            - run: make bench CFLAGS=-O3 DEBUG=0
