name: Test
on: [push]

jobs:
    macos:
        strategy:
            matrix:
                os: [macos-12, macos-11]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - run: brew install make
            - run: gmake build/feature.h
            - run: cat build/feature.h build/feature/*.log
            - run: gmake check V=1 DEBUG=3 WERROR=1 TESTFLAGS=-ct
            - run: gmake bench CFLAGS=-O3

    linux:
        strategy:
            matrix:
                os: [ubuntu-22.04, ubuntu-20.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - run: make build/feature.h
            - run: cat build/feature.h build/feature/*.log
            - run: make check V=1 DEBUG=3 WERROR=1 TESTFLAGS=-ct
            - run: make bench CFLAGS=-O3
