name: Test
on: [push]

env:
    V: 1
    DEBUG: 3
    WERROR: 1
    TESTFLAGS: -ct

jobs:
    macos:
        strategy:
            matrix:
                os: [macos-15, macos-14, macos-13]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
              with: {filter: "tree:0", fetch-depth: 0}
            - run: brew install make
            - run: gmake vvars
            - run: gmake build/gen/feature.h
            - run: cat build/gen/feature.h build/feature/*.log
            - run: gmake check
            - run: gmake bench CFLAGS=-O3 DEBUG=0

    linux:
        strategy:
            matrix:
                os: [ubuntu-24.04, ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
              with: {filter: "tree:0", fetch-depth: 0}
            - run: make vvars
            - run: make build/gen/feature.h
            - run: cat build/gen/feature.h build/feature/*.log
            - run: make check
            - run: make bench CFLAGS=-O3 DEBUG=0
