name: Test
on: [push]

jobs:
    macos:
        strategy:
            matrix:
                os: [macos-12, macos-11]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - run: brew install make
            - run: gmake check V=1 DEBUG=3 WERROR=1
            - run: gmake bench CFLAGS=-O3

    linux:
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-22.04, ubuntu-20.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: github/codeql-action/init@v2
              with: {languages: cpp, queries: +security-and-quality}
            - run: make check V=1 DEBUG=3 WERROR=1
            - run: make bench CFLAGS=-O3
            - uses: github/codeql-action/analyze@v2
