name: Test
on: [push]
jobs:
    check:
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3
            - run: brew install make
            - run: gmake check V=1 DEBUG=3 WERROR=1
